// SPDX-FileCopyrightText: 2026 Open Circuit Design, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// SPDX-License-Identifier: Apache-2.0

/*
 *-------------------------------------------------------------------------
 * openframe_project_wrapper ---
 *
 * RTL verilog definition of the user project area for the open-frame
 * version of the Caravel harness chip, IHP SG13CMOS5L process, dual voltage
 * (1.8V core, 3.3V pad) padframe.
 *
 * Written by Tim Edwards
 * February 2026
 *
 * This file is automatically generated.  Do not edit.
 *-------------------------------------------------------------------------
 */

// `default_nettype none

// There are 44 GPIO pads in the openframe definition.  This
// is fixed and corresponds to the standard pinout and
// packaging for the Caravel harness chip.

`define OPENFRAME_IO_PADS 44

module openframe_project_wrapper (
	`ifdef USE_POWER_PINS
		// Power buses
		inout  vddio,	// Core 5.0V supply
		inout  vssio,	// Core 5.0V ground
		inout  vccd,	// Core 3.3V supply
		inout  vssd,	// Core 3.3V ground
	`endif

	// Core infrastructure (padframe-facing pins)

	input  gpio1_in,
	output gpio1_out,
	output gpio1_ena,
	input  gpio1_one,
	input  gpio1_zero,
	input  spi_SDO_in,
	output spi_SDO_out,
	output spi_SDO_ena,
	input  spi_SDO_one,
	input  spi_SDO_zero,
	input  spi_SDI_in,
	output spi_SDI_out,
	output spi_SDI_ena,
	input  spi_SDI_one,
	input  spi_SDI_zero,
	input  spi_CSB_in,
	output spi_CSB_out,
	output spi_CSB_ena,
	input  spi_CSB_one,
	input  spi_CSB_zero,
	input  spi_SCK_in,
	output spi_SCK_out,
	output spi_SCK_ena,
	input  spi_SCK_one,
	input  spi_SCK_zero,
	input  UART_Rx_in,
	output UART_Rx_out,
	output UART_Rx_ena,
	input  UART_Rx_one,
	input  UART_Rx_zero,
	input  UART_Tx_in,
	output UART_Tx_out,
	output UART_Tx_ena,
	input  UART_Tx_one,
	input  UART_Tx_zero,
	inout  analog_io_7_esd,
	inout  analog_io_7,
	inout  analog_io_8_esd,
	inout  analog_io_8,
	inout  analog_io_9_esd,
	inout  analog_io_9,
	inout  analog_io_10_esd,
	inout  analog_io_10,
	inout  analog_io_11_esd,
	inout  analog_io_11,
	inout  analog_io_12_esd,
	inout  analog_io_12,
	inout  analog_io_13_esd,
	inout  analog_io_13,
	inout  analog_io_14_esd,
	inout  analog_io_14,
	inout  analog_io_15_esd,
	inout  analog_io_15,
	inout  analog_io_16_esd,
	inout  analog_io_16,
	inout  analog_io_17_esd,
	inout  analog_io_17,
	inout  analog_io_18_esd,
	inout  analog_io_18,
	inout  analog_io_19_esd,
	inout  analog_io_19,
	inout  analog_io_20_esd,
	inout  analog_io_20,
	inout  analog_io_21_esd,
	inout  analog_io_21,
	inout  analog_io_22_esd,
	inout  analog_io_22,
	inout  analog_io_23_esd,
	inout  analog_io_23,
	inout  analog_io_24_esd,
	inout  analog_io_24,
	inout  analog_io_25_esd,
	inout  analog_io_25,
	inout  analog_io_26_esd,
	inout  analog_io_26,
	inout  analog_io_27_esd,
	inout  analog_io_27,
	inout  analog_io_28_esd,
	inout  analog_io_28,
	inout  analog_io_29_esd,
	inout  analog_io_29,
	inout  analog_io_30_esd,
	inout  analog_io_30,
	inout  analog_io_31_esd,
	inout  analog_io_31,
	inout  analog_io_32_esd,
	inout  analog_io_32,
	inout  analog_io_33_esd,
	inout  analog_io_33,
	inout  analog_io_34_esd,
	inout  analog_io_34,
	inout  analog_io_35_esd,
	inout  analog_io_35,
	input  flash_io2_in,
	output flash_io2_out,
	output flash_io2_ena,
	input  flash_io2_one,
	input  flash_io2_zero,
	input  flash_io3_in,
	output flash_io3_out,
	output flash_io3_ena,
	input  flash_io3_one,
	input  flash_io3_zero,
	input  clock_in,
	input  flash_csb_in,
	output flash_csb_out,
	output flash_csb_ena,
	input  flash_csb_one,
	input  flash_csb_zero,
	input  flash_clk_in,
	output flash_clk_out,
	output flash_clk_ena,
	input  flash_clk_one,
	input  flash_clk_zero,
	input  flash_io0_in,
	output flash_io0_out,
	output flash_io0_ena,
	input  flash_io0_one,
	input  flash_io0_zero,
	input  flash_io1_in,
	output flash_io1_out,
	output flash_io1_ena,
	input  flash_io1_one,
	input  flash_io1_zero,
	input  gpio0_in,
	output gpio0_out,
	output gpio0_ena,
	input  gpio0_one,
	input  gpio0_zero,

	input  resetb_in,
	input  clock_in,
	input  option_in,
	input  [31:0] mask_rev
);

	// Declare a user project by defining HAS_USER_PROJECT
	// and specifying the "netlists.v" file to include the
	// RTL source code for it.

	`ifdef HAS_USER_PROJECT

	    /* The user is responsible for defining the user project
	     * instance and connecting the appropriate signals.  The
	     * user project itself is normally a schematic.
	     */

	`endif

endmodule
// `default_nettype wire
